car= ['xiaomi','wenjie','jike','biyadi','baoma','benchi','aodi']
print(car[0])
car.append('kaidilake')
print(car)
car.insert(0,'baoshijie')
print(car)
del car[0]
print(car)
car.pop()
print(car)
car.pop(3)
print(car)
car.remove('aodi')
print(car)
print(car.sort())
print(car.sort(reverse=True))
print(sorted(car))
car.reverse()
print(car)
print(f"{len(car)}")